<a href="https://colab.research.google.com/github/13194307/UTS_ML2019_ID13194307/blob/master/ML_A2/derivativesPlayground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import math

y = [1.0, 0.0, 0.0]
x = [0.2698, 0.3223, 0.4078]
n = len(y)
loss = (-1*sum((y[i]*np.log(x[i])/np.log(10)) + ((1-y[i])*np.log(1-x[i])) for i in range(n)))/n
print(loss)

0.4939731616062768


In [15]:
np.log(x)/np.log(10)

array([-0.56895805, -0.49173969, -0.38955278])

In [27]:
#y = [1, 0, 0, 0, 0]
#x = [0.1, 0.5, 0.1, 0.1, 0.2]

-1*sum(y[i]*np.log(x[i]) for i in range(n))

2.3025850929940455

In [0]:
#Derivative of dE1/dOut1

def dE_dSoftmax(prob, actual):
    n = len(actual)
    #return [actual[i]/prob[i] for i in range(len(actual))]
    return [-1*(actual[i]/prob[i]) + ((1 - actual[i])*(-1/(1-prob[i]))) for i in range(n)]
    

In [104]:
d1 = dE_dSoftmax(x, y)
d1

[-3.7064492216456637, -1.4755791648221928, -1.6886187098953054]

In [0]:
#Derivative of dOut1/dIn1

def dSoftmax_dDot(prob):
    n = len(prob)
    return [prob[i]-(prob[i]**2) for i in range(n)]

In [58]:
d2 = dSoftmax_dDot(x)
d2

[0.19700795999999998, 0.21842271, 0.24149916]

In [0]:
def dDot_dWeights(input_vector):
    return input_vector

In [0]:
input_vector = [ 0.31736485, -0.01150337, -0.01441997]
prob = [0.24822991, 0.12071242, 0.63105767]
actual = [1, 0, 0]

In [105]:
d1 = np.array(dE_dSigmoid(prob, actual))
d1

array([-4.0285234 , -1.13728435, -2.71045071])

In [106]:
d2 = np.array(dSigmoid_dDot(prob))
d2

array([0.18661182, 0.10614093, 0.23282389])

In [107]:
d3 = np.array(dDot_dWeights(input_vector))
d3

array([ 0.31736485, -0.01150337, -0.01441997])

In [114]:
d1*d2*d3*0.01

array([-2.38585402e-03,  1.38859963e-05,  9.09983267e-05])

In [0]:
def dReLU_dDot(input_vector):
    derivative = np.array(input_vector)
    derivative[derivative > 0] = 1
    derivative[derivative <= 0] = 0.01
    return derivative

In [111]:
ReLU_values = [0.6, 0.4, 0.2, 0, -0.01, -0.5]
d4 = dReLU_dDot(ReLU_values)
d4

array([1.  , 1.  , 1.  , 0.01, 0.01, 0.01])

In [0]:
def dDot_dInputVector(weights):
    return weights